### ISSUE TITLE
tiny tiny rss webapp 

### ISSUE THREAD

**Issue by matueranet** [cznweb/genesis#183]
I have started on a tinytinyrss webapp plugin, but I have too little python experience and dont have the time to learn it and complete the plugin. If anyone is interested in completing it, fork the branch: https://github.com/matueranet/genesis/tree/tinytinyrss

The code is there, it is ready to do the first deployment test.

**Comment by peakwinter** [comment]
Closing in favour of issue on cznweb/arkos-applications
