### ISSUE TITLE
Backspace does not work reliably in the Terminal plugin

### ISSUE THREAD

**Issue by dbolton** [cznweb/genesis#194]
Sometimes when I open a new Terminal (using the plugin in Genesis), the backspace key works, other times it deletes two characters at a time, other times it prints a slash ("/") or a couple control characters ("^H^H").

I'm using Firefox 26.0 on Windows 7.

**Comment by peakwinter** [comment]
No longer applies as we'll be switching to an external app (`tty.js`) for >0.7.
