### ISSUE TITLE
Certificate generation

### ISSUE THREAD

**Issue by ghost** [cznweb/genesis#410]
When trying to generate a certificate in genesis 0.6, I get the error:

"System time is too far off - offset is UNKNOWN"

**Comment by P3lUZa** [comment]
No coincidence, it also worked for me. I believe that since user has no admin privileges it can't add certificates and it throws a misleading message instead.

**Comment by peakwinter** [comment]
Genesis operates as root, and as such doesn't do anything with privilege escalation. Certificates are generated as root. If you also received that exact system time error message, that is due to a temporary DNS lookup error.
