### ISSUE TITLE
CPU usage alerts not properly evaluating safe range

### ISSUE THREAD

**Issue by peakwinter** [cznweb/genesis#432]
See https://bbs.arkos.io/t/cpu-alert-when-using-much-less-than-configured-amount/1046/2

**Comment by peakwinter** [comment]
If it's not fixed already in 0.6 it'll be fixed in 0.7 (switched to a new way of fetching value).

**Comment by Bugsbane** [comment]
Not sure if this was closed because of updates to the codebase, or because of my lack of reply. If it's because of the latter, it should be noted that I still see this issue in 0.6.2
