### ISSUE TITLE
Tor Plugin

### ISSUE THREAD

**Issue by X4fyr** [cznweb/genesis#492]
Hey,

I made a bit of a tor-plugin about a month ago,but now I don't have much time left because of my studies.
It is in an extra branch in my fork of this repo (https://github.com/X4fyr/genesis). I will look later, if it and what is actually functioning.

It is far from finished now, and not ready for a pull-request. So if someone is like to finish it, or use it as a starting point you are free to do. You don't have to mention my name if you do. As I said, its far from a finished plugin.

**Comment by peakwinter** [comment]
Thank you -- will follow up in #30!
