### ISSUE TITLE
Selecting "Download" from tools menu in File Manager is broken

### ISSUE THREAD

**Issue by derikk** [cznweb/genesis#493]
When checking a file or folder and selecting **Download...** from the **Tools** menu, Genesis shows a "Please wait..." dialog, but does not download anything.
### Tested
With Chrome 39 and Safari 8 on OS X 10.10, Genesis version 0.6.2
### Expected behavior
Genesis should initiate a download of the selected file or files, like clicking the download icon to the right of a file/folder does.
### Actual behavior
Genesis displays a "Please wait..." dialog for a few seconds, but does not initiate a download.

**Comment by peakwinter** [comment]
Fixed in 0.7
