### ISSUE TITLE
Perfect forward secrecy

### ISSUE THREAD

**Issue by HeinAtCERN** [cznweb/genesis#495]
Feature request:
I think it would be nice, if we could help the user to enable PFS, or even enable it by default. Here's was a discussion on the bbs: https://bbs.arkos.io/t/enable-ssl-forward-secrecy-with-nginx/712
I'm not exactly sure on how to implement it. Maybe by opening a message box that asks for it, when a certificate is assigned to a website.

Cheers! -Heiner

**Comment by peakwinter** [comment]
The new default ciphers are PFS-friendly by default. Thanks!

**Comment by HeinAtCERN** [comment]
Does it mean, that PFS is enabled by default?

**Comment by peakwinter** [comment]
Yes that is correct.
