### ISSUE TITLE
Notepad needs to reopen file to show content

### ISSUE THREAD

**Issue by amo13** [cznweb/genesis#500]
Reproduce:
use the file manager to select a file and open it (select one that opens automatically in the notepad),
go back to the file manager and open another file (opens in notepad in a new tab),
in the notepad switch back to the first tab and the text will be gone

using Genesis 0.6.2 on a cubietruck

**Comment by peakwinter** [comment]
The notepad in 0.7 is integrated into the File Manager and no longer uses tabs, so this issue is no longer valid. It may be added back if there is enough interest in this feature.

Thanks for reporting!
