### ISSUE TITLE
Genesis crash: problem with authorized_keys file

### ISSUE THREAD

**Issue by stevenroose** [cznweb/genesis#501]
This is the error message from Genesis:

https://gist.github.com/stevenroose/a72ff6e4153b1e6bcabb

**Comment by stevenroose** [comment]
It happens when I click the SSH option and results in all of the other pages failing as well. Starting a new session is the only solution.

**Comment by peakwinter** [comment]
Hi Steven,

It looks like you're running a pretty old version of Genesis (pre-0.6). This error has been fixed in the latest version of the software. You can find update instructions here: https://arkos.io/2014/07/genesis-0-6-panoply-released/

Please let me know if that solves it for you!

Thanks

**Comment by stevenroose** [comment]
I used the latest Vagrant box from the website. (I also asked in the IRC channel why 0.5.1 was in this box while I saw news posts about v0.7.)
Will the vagrant dev box on the website be updated?

I'll just use the migration tool on the page you mentioned.

**Comment by peakwinter** [comment]
Ah yes! I definitely will update it as soon as I can; I've been a little remiss on that as I've been so busy with 0.7. Thanks for reminding me :)
