### ISSUE TITLE
XMPP/Prosody: unable to start the process

### ISSUE THREAD

**Issue by amo13** [cznweb/genesis#504]
I installed the XMPP app, went into "my applications" and "chat xmpp" and saw the red status button. After clicking it I enabled prosody and then started it. Then, on the config page for XMPP I enabled "allow registration" and disabled "force encryption" and then saved. After saving was done the status button was red again and clicking it revealed that prosody has stopped. From now I am unable to start it because clicking the little play button to start the process does nothing. The status windows disappears after a short loading time but the status button remains red and prosody didn't start.
I tried figuring out where to find the log file but unfortunately I wasn't successful. In the config of prosody (/etc/prosody/prosody.cfg.lua) I changed the some lines to the following:

log = {
	info = "/var/log/prosody/prosody.log"; -- Change 'info' to 'debug' for verbose logging
	error = "/var/log/prosody/prosody.err";

but I still can't find any log file... tried restarting the system but I don't get any changes.

**Comment by peakwinter** [comment]
You can get more information about the error state with `sudo systemctl status -l prosody` or, in the case of an error in the config file (which is the most likely), try `luac5.1 -p /etc/prosody/prosody.cfg.lua`

**Comment by amo13** [comment]
The first command gives me the following output:
![systemctl_prosody](https://cloud.githubusercontent.com/assets/6617661/6987713/74ec57dc-da4a-11e4-84b5-ef8d6498899e.png)

while the second gave me no output. It doesn't seem that anything has changed. The process still doesn't start and I still can't find a log file.

**Comment by peakwinter** [comment]
Sorry for the delay. Is this still happening? You may need to create the folder at `/var/log/prosody` and make it owned by `prosody` before it will be able to write logs there.

**Comment by amo13** [comment]
Yes, the problem persists, but you were right about the logs: now I can show you what they say:
Apr 16 09:43:37 general	error	No enabled VirtualHost entries found in the config file.
Apr 16 09:43:37 general	error	At least one active host is required for Prosody to function. Exiting...
I don't really understand what this means... Is this a problem with the plugin or just something on my server?
On Apr 14, 2015 1:24 AM, Jacob Cook <notifications@github.com> wrote:Sorry for the delay. Is this still happening? You may need to create the folder at /var/log/prosody and make it owned by prosody before it will be able to write logs there.

**Comment by peakwinter** [comment]
That means you need to add domains via the XMPP server app in Genesis before the process itself will be able to start.

**Comment by amo13** [comment]
oh, well that's a bit embarassing x) sorry for that...
but there is still another problem: now that the server is running and a domain is activated, it won't let me register an account from within conversations (android) or pidgin (linux). Conversations says "incompatible server" and pidgin tells "You require encryption, but it is not available on this server.". I tried with and without encryption ticked in the genesis plugin. 
If I create the account in the genesis plugin pidgin is able to connect, conversations unfortunately keeps saying the server is not compatible.

**Comment by peakwinter** [comment]
By default, accounts cannot be added via clients; you must set them up via the Genesis plugin. If your client is set to require encryption (which it sounds like it is set to do) you will also need to add an SSL certificate to the XMPP service via the Certificates pane to add encryption.

**Comment by amo13** [comment]
hm ok, since I didn't touch encryption yet, I think I will try this again later.
Thanks!
