### ISSUE TITLE
Websites fail to install on Genesis 0.7 (Vagrant)

### ISSUE THREAD

**Issue by Bugsbane** [cznweb/genesis#505]
Using the latest vagrant box, I get this error when trying to install ownCloud:

--------------------------------------------------------------------------------
ERROR in utilities [/home/vagrant/kraken/kraken/utilities.py:34]:
Job 22f13ace7d4c4a9f (_post) has run into exception Exception: nginx serverblock couldn't be written - cannot concatenate 'str' and 'NoneType' objects
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in utilities [/home/vagrant/kraken/kraken/utilities.py:35]:
Stacktrace is as follows:
Traceback (most recent call last):
  File "/home/vagrant/kraken/kraken/utilities.py", line 29, in run
    self._func(*self._args, **self._kwargs)
  File "/home/vagrant/kraken/kraken/frameworks/sites.py", line 39, in _post
    specialmsg = site.install(app, data["extra_data"], True, message)
  File "/home/vagrant/core/arkos/websites.py", line 202, in install
    raise Exception('nginx serverblock couldn\'t be written - '+str(e))
Exception: nginx serverblock couldn't be written - cannot concatenate 'str' and 'NoneType' objects

--------------------------------------------------------------------------------

There doesn't seem to be anything in /var/log/genesis.log

**Comment by peakwinter** [comment]
Note to self, see https://github.com/cznweb/genesis/issues/453#issuecomment-93594937

**Comment by peakwinter** [comment]
Should be fixed in latest push.
