### ISSUE TITLE
[Usability] [Minor] It's unclear that clicking in the file manager will do anything

### ISSUE THREAD

**Issue by Bugsbane** [cznweb/genesis#508]
Going into the file manager, it doesn't look like clicking on any of the files or folders will do anything, because the cursor doesn't change to the typical hand icon, people expect to see when hovering over a link or interactive item.

**Comment by peakwinter** [comment]
Good idea, will take a look. Thanks!

(BTW, try right-clicking the folders too ;) )

**Comment by peakwinter** [comment]
Fixed in latest release.
