### ISSUE TITLE
Generating certificate can't find .pem file

### ISSUE THREAD

**Issue by Bugsbane** [cznweb/genesis#510]
When I try to generate a certificate using all the default settings, except putting in an address, I get the following error in the console:

--------------------------------------------------------------------------------
ERROR in utilities [/home/vagrant/kraken/kraken/utilities.py:34]:
Job 53866810ec78518c (_generate) has run into exception IOError: [Errno 2] No such file or directory: u'/etc/arkos/ssl/ca_certs/1234 Mystreet Rd.pem'
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
ERROR in utilities [/home/vagrant/kraken/kraken/utilities.py:35]:
Stacktrace is as follows:
Traceback (most recent call last):
  File "/home/vagrant/kraken/kraken/utilities.py", line 29, in run
    self._func(*self._args, **self._kwargs)
  File "/home/vagrant/kraken/kraken/frameworks/certificates.py", line 48, in _generate
    data["keytype"], data["keylength"])
  File "/home/vagrant/core/arkos/certificates.py", line 221, in generate_certificate
    ca = generate_authority(basehost)
  File "/home/vagrant/core/arkos/certificates.py", line 294, in generate_authority
    with open(ca.cert_path, "wt") as f:
IOError: [Errno 2] No such file or directory: u'/etc/arkos/ssl/ca_certs/1234 Mystreet Rd.pem'

--------------------------------------------------------------------------------

**Comment by peakwinter** [comment]
Good catch, the `/etc/arkos/ssl/ca_certs` doesn't exist automatically in the Vagrant image either. Will fix. Thanks!

**Comment by peakwinter** [comment]
Should be fixed in latest push.
