### ISSUE TITLE
Genesis test server fails to start after today's updates

### ISSUE THREAD

**Issue by Bugsbane** [cznweb/genesis#513]
Yesterday the ArkOS vagrant server was working for me. I had to shut it down, and after I rebooted I did vagrant up which pulled the latest sources. Everything went fine until I did sudo ./arkostest.sh which listed a number of generally positive sounding messages such as:
--------------------------------------------------------------------------------
DEBUG in framework [/home/vagrant/kraken/kraken/framework.py:12]:
 *** Registering roles...
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in framework [/home/vagrant/kraken/kraken/framework.py:12]:
 *** Registering packages...
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in framework [/home/vagrant/kraken/kraken/framework.py:12]:
 *** Registering apps...
--------------------------------------------------------------------------------
--------------------------------------------------------------------------------
DEBUG in framework [/home/vagrant/kraken/kraken/framework.py:12]:
 *** Registering services...
--------------------------------------------------------------------------------

after that though, I get the following trace:
Traceback (most recent call last):
  File "krakend", line 85, in <module>
    run_daemon(environment, log_level, config_file)
  File "/home/vagrant/kraken/kraken/application.py", line 69, in run_daemon
    app.register_blueprint(genesis.backend)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 62, in wrapper_func
    return f(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 889, in register_blueprint
    blueprint.register(self, options, first_registration)
  File "/usr/lib/python2.7/site-packages/flask/blueprints.py", line 153, in register
    deferred(state)
  File "/home/vagrant/kraken/kraken/genesis.py", line 43, in genesis_init
    genesis_build()
  File "/home/vagrant/kraken/kraken/genesis.py", line 46, in genesis_build
    for x in os.listdir(os.path.join(path, 'lib')):
NameError: global name 'path' is not defined

...and the server doesn't start any more.

**Comment by peakwinter** [comment]
Whoops! Try halting and re-upping now?
