### ISSUE TITLE
Typo on Step 4 in the "Welcome to arkOS" wizard

### ISSUE THREAD

**Issue by mplorentz** [cznweb/genesis#515]
The text blurb at the top of the screen says to "click Setup" but there is no "Setup" button, only a "Start" button.
![2015-04-22 at 11 50 am](https://cloud.githubusercontent.com/assets/1165004/7278816/d0d7cf96-e8e5-11e4-8c02-27ec65a2b6fa.png)

**Comment by peakwinter** [comment]
Good catch, thanks :)
