### ISSUE TITLE
App failed to load — Module error: No module named MySQLdb, breaks owncloud on clean install

### ISSUE THREAD

**Issue by lightnin** [cznweb/genesis#518]
Clean install of 0.7 beta 3 on Rpi2, selected owncloud to be installed on first run. 

App store tab now shows "owncloud" status: uninstall (which presumably indicates it is installed). 
Home tab does not show application. New site dialog does not provide options (so next button cannot be pressed).

I then asked the system to update all packages. After which I noticed:

Selecting info on "MariaDb" on app store indicates:
App failed to load — Module error: No module named MySQLdb
Owncloud reports: App failed to load — Depends on MariaDB, which also failed

Thereafter, the system hung - never completed update of packages I guess. After hard reboot, cannot login - login screen says "unknown error, please check server."

Thanks for all the work you put into this - it's a great concept. :)

![screenshot from 2015-06-06 14 10 41](https://cloud.githubusercontent.com/assets/1538027/8019599/5732000e-0c57-11e5-9eeb-e658f819c323.png)

![screenshot from 2015-06-06 13 57 20](https://cloud.githubusercontent.com/assets/1538027/8019558/1725643a-0c55-11e5-9f12-cfa7c1410c78.png)

![screenshot from 2015-06-06 14 04 33](https://cloud.githubusercontent.com/assets/1538027/8019555/fea3d93c-0c54-11e5-8cf2-5af0767e5aec.png)

**Comment by peakwinter** [comment]
Hi there,

After initially installing applications, some may require a reboot of arkOS (like MariaDB does), because they include libraries that arkOS needs itself to manage said applications. A message should have come up with this after the installation was done but I don't think it is very clear or sticks around for very long... so that needs to be changed.

At any rate, have you tried restarting the device?


Hope that helps!

**Comment by lightnin** [comment]
I did try restarting, but it seems to be borked now with "unknown error - please check server."
I did expect a restart, as the setup screen indicated there would be one. But I don't believe it ever happened.
I can get you logs if you like. I'm not attached to this install - I can just start over. But if you need logs or something to try and nail it down, let me know.

**Comment by peakwinter** [comment]
I see a bug that may have caused that; I will get it into the release I push soon. Thank you!
