### ISSUE TITLE
[v0.7] Problem - The genesis webinterface did not start on boot

### ISSUE THREAD

**Issue by Jeeppler** [cznweb/genesis#520]
I downloaded the latest Raspberry Pi (orginal) image and copied it via dd to the SD-Card, but the web interface did not start on boot even after rebooting. Only the ssh and ldap port are open after booting up. 

Which debug/log files are interesting to be able to provide more information?

**Comment by Jeeppler** [comment]
How can I start the Genesis web interface manually?

**Comment by peakwinter** [comment]
You can check the log file at `/var/log/kraken.log`, or start the interface manually with `sudo systemctl start krakend`.

**Comment by Jeeppler** [comment]
You can find the `kraken.log` and `systemctl -l status krakend` output in the gist:
https://gist.github.com/Jeeppler/fce04d71844e5408ab26
maybe this is useful for you.

After starting kraken via `sudo systemctl start krakend` kraken was running fine. Than I restarted the system and after the reboot the kraken service was started. But the nginx server was not started on port 8888.

After some time the kraken service crashes.
